// Generated by delombok at Tue Aug 27 12:36:33 CEST 2013
package lombok.delegate.test;

public class Delegator implements DelegateInterface {
	
	DelegateClass d;
	
	@java.lang.SuppressWarnings("all")
	public <I extends lombok.delegate.test.InterfaceA & lombok.delegate.test.InterfaceB> void method(final I arg) {
		this.d.<I>method(arg);
	}
}